# Generated by Django 4.0.10 on 2023-04-06 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_id_alter_customuser_temp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='temp_id',
            new_name='custom_id',
        ),
    ]
