# Generated by Django 4.0.10 on 2023-04-25 03:19

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('temperature', models.DecimalField(decimal_places=1, default=1, max_digits=2, validators=[django.core.validators.MaxValueValidator(1.5, '1.5 is the maximum temperature'), django.core.validators.MinValueValidator(0.1, '0.1 is the manimum temperature')])),
                ('sys_messages', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatboxes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_msg', models.TextField(verbose_name='user message content')),
                ('assistant_msg', models.TextField(verbose_name='assistant message content')),
                ('n_prompt_messages', models.IntegerField(default=0, verbose_name='prompt messages length')),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='prompt messages tokens')),
                ('user_msg_tokens', models.IntegerField(default=0, verbose_name='user message tokens')),
                ('assistant_msg_tokens', models.IntegerField(default=0, verbose_name='assistant message tokens')),
                ('finish_reason', models.CharField(blank=True, max_length=10, null=True)),
                ('voice_message', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_credits', models.IntegerField(default=0)),
                ('chatbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatv1.chatbox')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatmessages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
