# Generated by Django 4.0.10 on 2023-04-25 22:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatv1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbox',
            name='sys_messages',
        ),
        migrations.AddField(
            model_name='chatbox',
            name='sys_message',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='chatbox',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='chatbox',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
