# Generated by Django 4.0.10 on 2023-04-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatv1', '0002_remove_chatbox_sys_messages_chatbox_sys_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='finish_reason',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
