# Generated by Django 4.0.10 on 2023-04-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatv1', '0004_alter_chatbox_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='user_msg',
            field=models.TextField(blank=True, verbose_name='user message content'),
        ),
    ]
