# Generated by Django 4.0.10 on 2023-05-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatv1', '0005_alter_chatmessage_user_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbox',
            name='sys_message',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
